version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    environment:
      DB_URI: mongodb://db_container:27017
      PORT: 5000
      DB_NAME: ekoso
    depends_on:
      - mongo
  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}